## Arrays vs Lists

list looks like an array but works generic data structure  but numpy array is used specifically for math operations

In [3]:
import numpy as np
L = [1,2,3]

In [4]:
A = np.array([1,2,3])
A = np.array(L)


In [4]:
print(type(L))
print(type(A))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
for e in L:
    print(e)

1
2
3


In [ ]:
for e in A:
    print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4) # doesn't work

AttributeError: ignored

Size of list can change but size of array is fixed once defined

In [ ]:
L + [5]  # list concatenation

[1, 2, 3, 4, 5]

In [5]:
A + np.array([4])  # addition of vectors 

array([5, 6, 7])

In [6]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5]) 
# doesn't work because we can not add vetors of diffrent sizes

ValueError: ignored

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
    L2.append(e + 3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = []
for e in L:
    L2.append(e**2)

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a, b):
    dot += e*f
dot

11

In [ ]:
# use integer index
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
b.dot(a)

11

In [ ]:
a @ b

11

## Matrices

array can be of any dimensions but matrix must be least two
in matrix rows come first then the coloums

In [ ]:
# create 2 by 2 matrix
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0] # all row 0th col

array([1, 3])

In [ ]:
A.T # transpose of A

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)  
# in list if we use exp using numpy  it will return u array

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
# create matrix
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# matrix dot product
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
# error! inner dimensions must match in matrix multiplication
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.diag(A) # gives diagonal element

array([1, 4])

In [ ]:
np.diag([1, 4]) # creates diagonal matrix

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A) # returns eigen values and eigen vectors

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

## Generating Data

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.random()  

0.3276152173767566

In [5]:
np.random.random((2, 3))  # normal distribution

array([[0.53987729, 0.26661944, 0.31955939],
       [0.44101615, 0.16999733, 0.87901222]])

In [6]:
np.random.randn(2, 3)  # gausian distribution

array([[-0.80699105, -1.5209502 , -2.23775407],
       [-1.22773878, -0.16065302,  0.79159029]])

In [5]:
R = np.random.randn(10000)  # generate array of 10000 elements calulate mean

In [6]:
R.size

10000

In [8]:
R.mean()

-0.01195482879938827

In [9]:
np.mean(R)

-0.01195482879938827

In [10]:
R.var()

0.9894410342044806

In [11]:
R.std()

0.9947065065658717

In [ ]:
R = np.random.randn(10000, 3) # (row,col)

In [ ]:
R.mean(axis=0)   # col

array([-0.00671182, -0.0086458 , -0.01834377])

In [ ]:
R.mean(axis=1).shape # row

(10000,)

In [12]:
np.cov(R)  
# cov treat each col as vector observations

array(0.98953999)

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T) # we can take transpose to see the observations

array([[ 0.98396137,  0.00432999,  0.01031152],
       [ 0.00432999,  0.99723915, -0.004402  ],
       [ 0.01031152, -0.004402  ,  0.99895114]])

In [ ]:
np.random.randint(0, 10, size=(3, 3))

array([[6, 1, 2],
       [9, 7, 8],
       [4, 8, 1]])

In [6]:
np.random.choice(10, size=(3, 3))

array([[4, 2, 9],
       [9, 5, 0],
       [4, 0, 1]])

# Where to learn more Numpy 
https://numpy.org/doc/1.20/user/whatisnumpy.html

Great Job!